// Code generated by go-swagger; DO NOT EDIT.

package main

import (
	"log"
	"os"
	"strconv"

	"github.com/go-openapi/loads"

	"github.com/joho/godotenv"

	"msa-bank-client/restapi"
	"msa-bank-client/restapi/operations"
)

func main() {
	err := godotenv.Load(".env")
	if err != nil {
		log.Fatalf("Error loading .env file")
	}

	swaggerSpec, err := loads.Embedded(restapi.SwaggerJSON, restapi.FlatSwaggerJSON)
	if err != nil {
		log.Fatalln(err)
	}

	api := operations.NewMsaBankClientCsAPI(swaggerSpec)
	server := restapi.NewServer(api)
	defer server.Shutdown()

	port := os.Getenv("SERVER_PORT")

	serverPort, err := strconv.Atoi(port)
	if err != nil {
		log.Fatalln(err)
	}

	server.Port = serverPort
	server.ConfigureAPI()

	if err := server.Serve(); err != nil {
		log.Fatalln(err)
	}

}
