
// Code generated by go-swagger; DO NOT EDIT.

package main

import (
	"flag"
	"log"

	"github.com/go-openapi/loads"

	"msa-bank-client/restapi"
	"msa-bank-client/restapi/operations"
)

var portFlag = flag.Int("port", 3000, "Port to run this service on")


// This file was generated by the swagger tool.
// Make sure not to overwrite this file after you generated it because all your edits would be lost!

func main() {

	swaggerSpec, err := loads.Embedded(restapi.SwaggerJSON, restapi.FlatSwaggerJSON)
	if err != nil {
		log.Fatalln(err)
	}

	api := operations.NewMsaBankClientCsAPI(swaggerSpec)
	server := restapi.NewServer(api)
	defer server.Shutdown()

	flag.Parse()
	// set the port this service will be run on
	server.Port = *portFlag

	server.ConfigureAPI()

	if err := server.Serve(); err != nil {
		log.Fatalln(err)
	}

}