// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.2 DO NOT EDIT.
package models

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// Account defines model for Account.
type Account struct {
	AccountNumber string              `json:"accountNumber"`
	Amount        float32             `json:"amount"`
	ClientId      openapi_types.UUID  `json:"clientId"`
	EndDate       string              `json:"endDate"`
	Id            *openapi_types.UUID `json:"id,omitempty"`
	StartDate     string              `json:"startDate"`
}

// ChangeAccountBalance defines model for ChangeAccountBalance.
type ChangeAccountBalance struct {
	RequestedAmount float32 `json:"requestedAmount"`
}

// AddAccountJSONRequestBody defines body for AddAccount for application/json ContentType.
type AddAccountJSONRequestBody = Account

// UpdateAccountJSONRequestBody defines body for UpdateAccount for application/json ContentType.
type UpdateAccountJSONRequestBody = Account

// UpdateAccountBalanceJSONRequestBody defines body for UpdateAccountBalance for application/json ContentType.
type UpdateAccountBalanceJSONRequestBody = ChangeAccountBalance
