// Code generated by go-swagger; DO NOT EDIT.

// Package restapi msa-bank-client-cs
//
//	This is a sample server for Clients.
//	Terms Of Service:
//	  http://swagger.io/terms/
//	Schemes:
//	  http
//	Host: msa-bank-client-cs.swagger.io
//	BasePath: /v1
//	Version: 1.0.0
//	License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
//	Contact: <apiteam@swagger.io>
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
