// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package models

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CreditCreditType.
const (
	Автокредит      CreditCreditType = "Автокредит"
	Ипотека         CreditCreditType = "Ипотека"
	Потребительский CreditCreditType = "Потребительский"
)

// AllPayment defines model for AllPayment.
type AllPayment = []PaymentPlan

// Credit defines model for Credit.
type Credit struct {
	Amount       float32            `json:"amount"`
	ClientId     openapi_types.UUID `json:"clientId"`
	CreditType   CreditCreditType   `json:"creditType"`
	Id           openapi_types.UUID `json:"id"`
	MonthPayment float32            `json:"monthPayment"`
	Months       int                `json:"months"`
	Rate         float32            `json:"rate"`
	TotalAmount  float32            `json:"totalAmount"`
}

// CreditCreditType defines model for Credit.CreditType.
type CreditCreditType string

// EarlyRepayment defines model for EarlyRepayment.
type EarlyRepayment struct {
	Amount float32            `json:"amount"`
	Id     openapi_types.UUID `json:"id"`
}

// FullRepayment defines model for FullRepayment.
type FullRepayment struct {
	Id openapi_types.UUID `json:"id"`
}

// PaymentPlan defines model for PaymentPlan.
type PaymentPlan struct {
	MonthPayment float32 `json:"monthPayment"`
	TotalAmount  float32 `json:"totalAmount"`
}

// Rate defines model for Rate.
type Rate struct {
	Amount *float32 `json:"amount,omitempty"`
	Months *int     `json:"months,omitempty"`
	Rate   *float32 `json:"rate,omitempty"`
}

// PostCreditJSONRequestBody defines body for PostCredit for application/json ContentType.
type PostCreditJSONRequestBody = Credit

// PostCreditEarlyRepaymentJSONRequestBody defines body for PostCreditEarlyRepayment for application/json ContentType.
type PostCreditEarlyRepaymentJSONRequestBody = EarlyRepayment

// PostCreditFullRepaymentJSONRequestBody defines body for PostCreditFullRepayment for application/json ContentType.
type PostCreditFullRepaymentJSONRequestBody = FullRepayment

// PostCreditPaymentPlanJSONRequestBody defines body for PostCreditPaymentPlan for application/json ContentType.
type PostCreditPaymentPlanJSONRequestBody = Rate
