// Code generated by go-swagger; DO NOT EDIT.

package client_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// AddClientHandlerFunc turns a function with the right signature into a add client handler
type AddClientHandlerFunc func(AddClientParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddClientHandlerFunc) Handle(params AddClientParams) middleware.Responder {
	return fn(params)
}

// AddClientHandler interface for that can handle valid add client params
type AddClientHandler interface {
	Handle(AddClientParams) middleware.Responder
}

// NewAddClient creates a new http.Handler for the add client operation
func NewAddClient(ctx *middleware.Context, handler AddClientHandler) *AddClient {
	return &AddClient{Context: ctx, Handler: handler}
}

/*
	AddClient swagger:route POST /client client-api addClient

Add a new client to the store
*/
type AddClient struct {
	Context *middleware.Context
	Handler AddClientHandler
}

func (o *AddClient) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewAddClientParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
