// Code generated by go-swagger; DO NOT EDIT.

package client_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"msa-bank-client/models"
)

// AddClientCreatedCode is the HTTP code returned for type AddClientCreated
const AddClientCreatedCode int = 201

/*
AddClientCreated successful operation

swagger:response addClientCreated
*/
type AddClientCreated struct {
	/*Authorization header

	 */
	Authorization string `json:"Authorization"`

	/*
	  In: Body
	*/
	Payload *models.Client `json:"body,omitempty"`
}

// NewAddClientCreated creates AddClientCreated with default headers values
func NewAddClientCreated() *AddClientCreated {

	return &AddClientCreated{}
}

// WithAuthorization adds the authorization to the add client created response
func (o *AddClientCreated) WithAuthorization(authorization string) *AddClientCreated {
	o.Authorization = authorization
	return o
}

// SetAuthorization sets the authorization to the add client created response
func (o *AddClientCreated) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithPayload adds the payload to the add client created response
func (o *AddClientCreated) WithPayload(payload *models.Client) *AddClientCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add client created response
func (o *AddClientCreated) SetPayload(payload *models.Client) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddClientCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Authorization

	authorization := o.Authorization
	if authorization != "" {
		rw.Header().Set("Authorization", authorization)
	}

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddClientMethodNotAllowedCode is the HTTP code returned for type AddClientMethodNotAllowed
const AddClientMethodNotAllowedCode int = 405

/*
AddClientMethodNotAllowed Invalid input

swagger:response addClientMethodNotAllowed
*/
type AddClientMethodNotAllowed struct {
}

// NewAddClientMethodNotAllowed creates AddClientMethodNotAllowed with default headers values
func NewAddClientMethodNotAllowed() *AddClientMethodNotAllowed {

	return &AddClientMethodNotAllowed{}
}

// WriteResponse to the client
func (o *AddClientMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}

// AddClientInternalServerErrorCode is the HTTP code returned for type AddClientInternalServerError
const AddClientInternalServerErrorCode int = 500

/*
AddClientInternalServerError Internal server error

swagger:response addClientInternalServerError
*/
type AddClientInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewAddClientInternalServerError creates AddClientInternalServerError with default headers values
func NewAddClientInternalServerError() *AddClientInternalServerError {

	return &AddClientInternalServerError{}
}

// WithPayload adds the payload to the add client internal server error response
func (o *AddClientInternalServerError) WithPayload(payload *models.Error) *AddClientInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add client internal server error response
func (o *AddClientInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddClientInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
