// Code generated by go-swagger; DO NOT EDIT.

package client_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteClientHandlerFunc turns a function with the right signature into a delete client handler
type DeleteClientHandlerFunc func(DeleteClientParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteClientHandlerFunc) Handle(params DeleteClientParams) middleware.Responder {
	return fn(params)
}

// DeleteClientHandler interface for that can handle valid delete client params
type DeleteClientHandler interface {
	Handle(DeleteClientParams) middleware.Responder
}

// NewDeleteClient creates a new http.Handler for the delete client operation
func NewDeleteClient(ctx *middleware.Context, handler DeleteClientHandler) *DeleteClient {
	return &DeleteClient{Context: ctx, Handler: handler}
}

/*
	DeleteClient swagger:route DELETE /client/{id} client-api deleteClient

# Delete client from the store

Delete client
*/
type DeleteClient struct {
	Context *middleware.Context
	Handler DeleteClientHandler
}

func (o *DeleteClient) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteClientParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
