// Code generated by go-swagger; DO NOT EDIT.

package client_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"msa-bank-client/models"
)

// DeleteClientOKCode is the HTTP code returned for type DeleteClientOK
const DeleteClientOKCode int = 200

/*
DeleteClientOK successful operation

swagger:response deleteClientOK
*/
type DeleteClientOK struct {
}

// NewDeleteClientOK creates DeleteClientOK with default headers values
func NewDeleteClientOK() *DeleteClientOK {

	return &DeleteClientOK{}
}

// WriteResponse to the client
func (o *DeleteClientOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteClientMethodNotAllowedCode is the HTTP code returned for type DeleteClientMethodNotAllowed
const DeleteClientMethodNotAllowedCode int = 405

/*
DeleteClientMethodNotAllowed Invalid input

swagger:response deleteClientMethodNotAllowed
*/
type DeleteClientMethodNotAllowed struct {
}

// NewDeleteClientMethodNotAllowed creates DeleteClientMethodNotAllowed with default headers values
func NewDeleteClientMethodNotAllowed() *DeleteClientMethodNotAllowed {

	return &DeleteClientMethodNotAllowed{}
}

// WriteResponse to the client
func (o *DeleteClientMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}

// DeleteClientInternalServerErrorCode is the HTTP code returned for type DeleteClientInternalServerError
const DeleteClientInternalServerErrorCode int = 500

/*
DeleteClientInternalServerError Internal server error

swagger:response deleteClientInternalServerError
*/
type DeleteClientInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteClientInternalServerError creates DeleteClientInternalServerError with default headers values
func NewDeleteClientInternalServerError() *DeleteClientInternalServerError {

	return &DeleteClientInternalServerError{}
}

// WithPayload adds the payload to the delete client internal server error response
func (o *DeleteClientInternalServerError) WithPayload(payload *models.Error) *DeleteClientInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete client internal server error response
func (o *DeleteClientInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteClientInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
