// Code generated by go-swagger; DO NOT EDIT.

package client_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"msa-bank-client/models"
)

// GetClientOKCode is the HTTP code returned for type GetClientOK
const GetClientOKCode int = 200

/*
GetClientOK successful operation

swagger:response getClientOK
*/
type GetClientOK struct {

	/*
	  In: Body
	*/
	Payload *models.Client `json:"body,omitempty"`
}

// NewGetClientOK creates GetClientOK with default headers values
func NewGetClientOK() *GetClientOK {

	return &GetClientOK{}
}

// WithPayload adds the payload to the get client o k response
func (o *GetClientOK) WithPayload(payload *models.Client) *GetClientOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get client o k response
func (o *GetClientOK) SetPayload(payload *models.Client) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetClientOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetClientMethodNotAllowedCode is the HTTP code returned for type GetClientMethodNotAllowed
const GetClientMethodNotAllowedCode int = 405

/*
GetClientMethodNotAllowed Invalid input

swagger:response getClientMethodNotAllowed
*/
type GetClientMethodNotAllowed struct {
}

// NewGetClientMethodNotAllowed creates GetClientMethodNotAllowed with default headers values
func NewGetClientMethodNotAllowed() *GetClientMethodNotAllowed {

	return &GetClientMethodNotAllowed{}
}

// WriteResponse to the client
func (o *GetClientMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}

// GetClientInternalServerErrorCode is the HTTP code returned for type GetClientInternalServerError
const GetClientInternalServerErrorCode int = 500

/*
GetClientInternalServerError Internal server error

swagger:response getClientInternalServerError
*/
type GetClientInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetClientInternalServerError creates GetClientInternalServerError with default headers values
func NewGetClientInternalServerError() *GetClientInternalServerError {

	return &GetClientInternalServerError{}
}

// WithPayload adds the payload to the get client internal server error response
func (o *GetClientInternalServerError) WithPayload(payload *models.Error) *GetClientInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get client internal server error response
func (o *GetClientInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetClientInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
