// Code generated by go-swagger; DO NOT EDIT.

package client_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetClientByPassportHandlerFunc turns a function with the right signature into a get client by passport handler
type GetClientByPassportHandlerFunc func(GetClientByPassportParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetClientByPassportHandlerFunc) Handle(params GetClientByPassportParams) middleware.Responder {
	return fn(params)
}

// GetClientByPassportHandler interface for that can handle valid get client by passport params
type GetClientByPassportHandler interface {
	Handle(GetClientByPassportParams) middleware.Responder
}

// NewGetClientByPassport creates a new http.Handler for the get client by passport operation
func NewGetClientByPassport(ctx *middleware.Context, handler GetClientByPassportHandler) *GetClientByPassport {
	return &GetClientByPassport{Context: ctx, Handler: handler}
}

/*
	GetClientByPassport swagger:route GET /client/find-by-passport/{passportNumber} client-api getClientByPassport

# Get client from the store by passport number

Get client by passport
*/
type GetClientByPassport struct {
	Context *middleware.Context
	Handler GetClientByPassportHandler
}

func (o *GetClientByPassport) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetClientByPassportParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
