// Code generated by go-swagger; DO NOT EDIT.

package client_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"msa-bank-client/models"
)

// GetClientsOKCode is the HTTP code returned for type GetClientsOK
const GetClientsOKCode int = 200

/*
GetClientsOK successful operation

swagger:response getClientsOK
*/
type GetClientsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Client `json:"body,omitempty"`
}

// NewGetClientsOK creates GetClientsOK with default headers values
func NewGetClientsOK() *GetClientsOK {

	return &GetClientsOK{}
}

// WithPayload adds the payload to the get clients o k response
func (o *GetClientsOK) WithPayload(payload []*models.Client) *GetClientsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get clients o k response
func (o *GetClientsOK) SetPayload(payload []*models.Client) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetClientsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Client, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetClientsMethodNotAllowedCode is the HTTP code returned for type GetClientsMethodNotAllowed
const GetClientsMethodNotAllowedCode int = 405

/*
GetClientsMethodNotAllowed Invalid input

swagger:response getClientsMethodNotAllowed
*/
type GetClientsMethodNotAllowed struct {
}

// NewGetClientsMethodNotAllowed creates GetClientsMethodNotAllowed with default headers values
func NewGetClientsMethodNotAllowed() *GetClientsMethodNotAllowed {

	return &GetClientsMethodNotAllowed{}
}

// WriteResponse to the client
func (o *GetClientsMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}

// GetClientsInternalServerErrorCode is the HTTP code returned for type GetClientsInternalServerError
const GetClientsInternalServerErrorCode int = 500

/*
GetClientsInternalServerError Internal server error

swagger:response getClientsInternalServerError
*/
type GetClientsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetClientsInternalServerError creates GetClientsInternalServerError with default headers values
func NewGetClientsInternalServerError() *GetClientsInternalServerError {

	return &GetClientsInternalServerError{}
}

// WithPayload adds the payload to the get clients internal server error response
func (o *GetClientsInternalServerError) WithPayload(payload *models.Error) *GetClientsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get clients internal server error response
func (o *GetClientsInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetClientsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
