// Code generated by go-swagger; DO NOT EDIT.

package client_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"msa-bank-client/models"
)

// UpdateClientOKCode is the HTTP code returned for type UpdateClientOK
const UpdateClientOKCode int = 200

/*
UpdateClientOK successful operation

swagger:response updateClientOK
*/
type UpdateClientOK struct {

	/*
	  In: Body
	*/
	Payload *models.Client `json:"body,omitempty"`
}

// NewUpdateClientOK creates UpdateClientOK with default headers values
func NewUpdateClientOK() *UpdateClientOK {

	return &UpdateClientOK{}
}

// WithPayload adds the payload to the update client o k response
func (o *UpdateClientOK) WithPayload(payload *models.Client) *UpdateClientOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update client o k response
func (o *UpdateClientOK) SetPayload(payload *models.Client) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateClientOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateClientBadRequestCode is the HTTP code returned for type UpdateClientBadRequest
const UpdateClientBadRequestCode int = 400

/*
UpdateClientBadRequest Invalid ID supplied

swagger:response updateClientBadRequest
*/
type UpdateClientBadRequest struct {
}

// NewUpdateClientBadRequest creates UpdateClientBadRequest with default headers values
func NewUpdateClientBadRequest() *UpdateClientBadRequest {

	return &UpdateClientBadRequest{}
}

// WriteResponse to the client
func (o *UpdateClientBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// UpdateClientNotFoundCode is the HTTP code returned for type UpdateClientNotFound
const UpdateClientNotFoundCode int = 404

/*
UpdateClientNotFound Client not found

swagger:response updateClientNotFound
*/
type UpdateClientNotFound struct {
}

// NewUpdateClientNotFound creates UpdateClientNotFound with default headers values
func NewUpdateClientNotFound() *UpdateClientNotFound {

	return &UpdateClientNotFound{}
}

// WriteResponse to the client
func (o *UpdateClientNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// UpdateClientMethodNotAllowedCode is the HTTP code returned for type UpdateClientMethodNotAllowed
const UpdateClientMethodNotAllowedCode int = 405

/*
UpdateClientMethodNotAllowed Validation exception

swagger:response updateClientMethodNotAllowed
*/
type UpdateClientMethodNotAllowed struct {
}

// NewUpdateClientMethodNotAllowed creates UpdateClientMethodNotAllowed with default headers values
func NewUpdateClientMethodNotAllowed() *UpdateClientMethodNotAllowed {

	return &UpdateClientMethodNotAllowed{}
}

// WriteResponse to the client
func (o *UpdateClientMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}

// UpdateClientInternalServerErrorCode is the HTTP code returned for type UpdateClientInternalServerError
const UpdateClientInternalServerErrorCode int = 500

/*
UpdateClientInternalServerError Internal server error

swagger:response updateClientInternalServerError
*/
type UpdateClientInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateClientInternalServerError creates UpdateClientInternalServerError with default headers values
func NewUpdateClientInternalServerError() *UpdateClientInternalServerError {

	return &UpdateClientInternalServerError{}
}

// WithPayload adds the payload to the update client internal server error response
func (o *UpdateClientInternalServerError) WithPayload(payload *models.Error) *UpdateClientInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update client internal server error response
func (o *UpdateClientInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateClientInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
