// Code generated by go-swagger; DO NOT EDIT.

package product_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"msa-bank-product/models"
)

// AddProductCreatedCode is the HTTP code returned for type AddProductCreated
const AddProductCreatedCode int = 201

/*
AddProductCreated successful operation

swagger:response addProductCreated
*/
type AddProductCreated struct {
}

// NewAddProductCreated creates AddProductCreated with default headers values
func NewAddProductCreated() *AddProductCreated {

	return &AddProductCreated{}
}

// WriteResponse to the client
func (o *AddProductCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// AddProductMethodNotAllowedCode is the HTTP code returned for type AddProductMethodNotAllowed
const AddProductMethodNotAllowedCode int = 405

/*
AddProductMethodNotAllowed Invalid input

swagger:response addProductMethodNotAllowed
*/
type AddProductMethodNotAllowed struct {
}

// NewAddProductMethodNotAllowed creates AddProductMethodNotAllowed with default headers values
func NewAddProductMethodNotAllowed() *AddProductMethodNotAllowed {

	return &AddProductMethodNotAllowed{}
}

// WriteResponse to the client
func (o *AddProductMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}

// AddProductInternalServerErrorCode is the HTTP code returned for type AddProductInternalServerError
const AddProductInternalServerErrorCode int = 500

/*
AddProductInternalServerError Internal server error

swagger:response addProductInternalServerError
*/
type AddProductInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewAddProductInternalServerError creates AddProductInternalServerError with default headers values
func NewAddProductInternalServerError() *AddProductInternalServerError {

	return &AddProductInternalServerError{}
}

// WithPayload adds the payload to the add product internal server error response
func (o *AddProductInternalServerError) WithPayload(payload *models.Error) *AddProductInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add product internal server error response
func (o *AddProductInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddProductInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
