// Code generated by go-swagger; DO NOT EDIT.

package product_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// AddProductHandlerFunc turns a function with the right signature into a add product handler
type AddProductHandlerFunc func(AddProductParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddProductHandlerFunc) Handle(params AddProductParams) middleware.Responder {
	return fn(params)
}

// AddProductHandler interface for that can handle valid add product params
type AddProductHandler interface {
	Handle(AddProductParams) middleware.Responder
}

// NewAddProduct creates a new http.Handler for the add product operation
func NewAddProduct(ctx *middleware.Context, handler AddProductHandler) *AddProduct {
	return &AddProduct{Context: ctx, Handler: handler}
}

/*
	AddProduct swagger:route POST /product product-api addProduct

Add a new product to the store
*/
type AddProduct struct {
	Context *middleware.Context
	Handler AddProductHandler
}

func (o *AddProduct) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewAddProductParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
