// Code generated by go-swagger; DO NOT EDIT.

package product_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"msa-bank-product/models"
)

// DeleteProductOKCode is the HTTP code returned for type DeleteProductOK
const DeleteProductOKCode int = 200

/*
DeleteProductOK successful operation

swagger:response deleteProductOK
*/
type DeleteProductOK struct {
}

// NewDeleteProductOK creates DeleteProductOK with default headers values
func NewDeleteProductOK() *DeleteProductOK {

	return &DeleteProductOK{}
}

// WriteResponse to the client
func (o *DeleteProductOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteProductMethodNotAllowedCode is the HTTP code returned for type DeleteProductMethodNotAllowed
const DeleteProductMethodNotAllowedCode int = 405

/*
DeleteProductMethodNotAllowed Invalid input

swagger:response deleteProductMethodNotAllowed
*/
type DeleteProductMethodNotAllowed struct {
}

// NewDeleteProductMethodNotAllowed creates DeleteProductMethodNotAllowed with default headers values
func NewDeleteProductMethodNotAllowed() *DeleteProductMethodNotAllowed {

	return &DeleteProductMethodNotAllowed{}
}

// WriteResponse to the client
func (o *DeleteProductMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}

// DeleteProductInternalServerErrorCode is the HTTP code returned for type DeleteProductInternalServerError
const DeleteProductInternalServerErrorCode int = 500

/*
DeleteProductInternalServerError Internal server error

swagger:response deleteProductInternalServerError
*/
type DeleteProductInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteProductInternalServerError creates DeleteProductInternalServerError with default headers values
func NewDeleteProductInternalServerError() *DeleteProductInternalServerError {

	return &DeleteProductInternalServerError{}
}

// WithPayload adds the payload to the delete product internal server error response
func (o *DeleteProductInternalServerError) WithPayload(payload *models.Error) *DeleteProductInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete product internal server error response
func (o *DeleteProductInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteProductInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
