// Code generated by go-swagger; DO NOT EDIT.

package product_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"msa-bank-product/models"
)

// GetProductsOKCode is the HTTP code returned for type GetProductsOK
const GetProductsOKCode int = 200

/*
GetProductsOK successful operation

swagger:response getProductsOK
*/
type GetProductsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Product `json:"body,omitempty"`
}

// NewGetProductsOK creates GetProductsOK with default headers values
func NewGetProductsOK() *GetProductsOK {

	return &GetProductsOK{}
}

// WithPayload adds the payload to the get products o k response
func (o *GetProductsOK) WithPayload(payload []*models.Product) *GetProductsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get products o k response
func (o *GetProductsOK) SetPayload(payload []*models.Product) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetProductsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Product, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetProductsMethodNotAllowedCode is the HTTP code returned for type GetProductsMethodNotAllowed
const GetProductsMethodNotAllowedCode int = 405

/*
GetProductsMethodNotAllowed Invalid input

swagger:response getProductsMethodNotAllowed
*/
type GetProductsMethodNotAllowed struct {
}

// NewGetProductsMethodNotAllowed creates GetProductsMethodNotAllowed with default headers values
func NewGetProductsMethodNotAllowed() *GetProductsMethodNotAllowed {

	return &GetProductsMethodNotAllowed{}
}

// WriteResponse to the client
func (o *GetProductsMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}

// GetProductsInternalServerErrorCode is the HTTP code returned for type GetProductsInternalServerError
const GetProductsInternalServerErrorCode int = 500

/*
GetProductsInternalServerError Internal server error

swagger:response getProductsInternalServerError
*/
type GetProductsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetProductsInternalServerError creates GetProductsInternalServerError with default headers values
func NewGetProductsInternalServerError() *GetProductsInternalServerError {

	return &GetProductsInternalServerError{}
}

// WithPayload adds the payload to the get products internal server error response
func (o *GetProductsInternalServerError) WithPayload(payload *models.Error) *GetProductsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get products internal server error response
func (o *GetProductsInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetProductsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
