// Code generated by go-swagger; DO NOT EDIT.

package product_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"msa-bank-product/models"
)

// GetProductOKCode is the HTTP code returned for type GetProductOK
const GetProductOKCode int = 200

/*
GetProductOK successful operation

swagger:response getProductOK
*/
type GetProductOK struct {

	/*
	  In: Body
	*/
	Payload *models.Product `json:"body,omitempty"`
}

// NewGetProductOK creates GetProductOK with default headers values
func NewGetProductOK() *GetProductOK {

	return &GetProductOK{}
}

// WithPayload adds the payload to the get product o k response
func (o *GetProductOK) WithPayload(payload *models.Product) *GetProductOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get product o k response
func (o *GetProductOK) SetPayload(payload *models.Product) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetProductOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetProductMethodNotAllowedCode is the HTTP code returned for type GetProductMethodNotAllowed
const GetProductMethodNotAllowedCode int = 405

/*
GetProductMethodNotAllowed Invalid input

swagger:response getProductMethodNotAllowed
*/
type GetProductMethodNotAllowed struct {
}

// NewGetProductMethodNotAllowed creates GetProductMethodNotAllowed with default headers values
func NewGetProductMethodNotAllowed() *GetProductMethodNotAllowed {

	return &GetProductMethodNotAllowed{}
}

// WriteResponse to the client
func (o *GetProductMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}

// GetProductInternalServerErrorCode is the HTTP code returned for type GetProductInternalServerError
const GetProductInternalServerErrorCode int = 500

/*
GetProductInternalServerError Internal server error

swagger:response getProductInternalServerError
*/
type GetProductInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetProductInternalServerError creates GetProductInternalServerError with default headers values
func NewGetProductInternalServerError() *GetProductInternalServerError {

	return &GetProductInternalServerError{}
}

// WithPayload adds the payload to the get product internal server error response
func (o *GetProductInternalServerError) WithPayload(payload *models.Error) *GetProductInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get product internal server error response
func (o *GetProductInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetProductInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
